//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_salary_date
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public decimal SalaryPaid { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
